title: Nonexistence
description: An undiscovered blog drifting through emptiness
author: WST
email: wanderingspacetraveler@gmail.com
logo: /static/img/milky-way.png
about: Wandering Space Thinker

baseurl: ""
url: "https://www.nonexistence.xyz/"

allowsearch: true
allowgoogleanalytics: true

disqus_shortname:
google_analytics:
google_tag: G-B9BM2328YD

share:
  twitter_username: WanderingSpace1
  fb_appid: 000000000000

paginate: 10
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist

exclude: [README.md, Gemfile, Gemfile.lock]