title: A blog drifting through emptiness
description: This little piece of digital space is my thoughts' harbor
author: WST
email: wanderingspacetraveler@gmail.com
logo: /nonexistence/static/img/milky-way.png
about: Wandering Space Thinker

baseurl: "/nonexistence"
url: "https://wanderingspacethinker.github.io"

allowsearch: true
allowgoogleanalytics: true

disqus_shortname:
google_analytics:

share:
  twitter_username: WanderingSpace1
  fb_appid: 000000000000

paginate: 5
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist